title: Zhisen Lai | PhD Researcher
first_name: Zhisen
last_name: Lai
description: >
  PhD Student in Computing & Information Science @ University of Nebraska Omaha.
  Interested in AI-enhanced scientific compression and Physics-informed Machine Learning.
url: https://SamLai0509.github.io 
baseurl: ""

scholar:
  last_name: [Lai]
  first_name: [Zhisen, Z.]
  style: apa
  source: /_bibliography/
  bibliography: papers.bib

enable_google_scholar: true 
enable_darkmode: true 
enable_navbar_social: true 

include: ["_pages", "_scripts"]
plugins:
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-link-attributes
  - jekyll/scholar
  - jekyll-sitemap
