# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Zhisen Lai | PhD Researcher
first_name: Zhisen
middle_name:
last_name: Lai
description: >
  PhD Student in Computing & Information Science @ University of Nebraska Omaha.
url: https://SamLai0509.github.io
baseurl: ""
lang: en

# -----------------------------------------------------------------------------
# Social Media Links
# -----------------------------------------------------------------------------
email: zhisenlai@unomaha.edu
scholar_userid: rwdaufcAAAAJ
github_username: SamLai0509
linkedin_username: zhisenlai

# -----------------------------------------------------------------------------
# Theme & Layout
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark
navbar_fixed: true
footer_fixed: true
max_width: 930px

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------
scholar:
  last_name: [Lai]
  first_name: [Zhisen, Z.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  query: "@*"
  group_by: year
  group_order: descending

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------
enable_google_scholar: true
enable_darkmode: true
enable_navbar_social: true

# -----------------------------------------------------------------------------
# Includes & Excludes
# -----------------------------------------------------------------------------
include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------

    
  # -----------------------------------------------------------------------------
  # Third-party libraries
  # -----------------------------------------------------------------------------
third_party_libraries:
  node_modules_load: false
  
plugins:
  - jekyll-3rd-party-libraries
  - jekyll-archives
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-scholar
  - jekyll-sitemap# ------------------------------------------------  node_modules_load: false
  # third_party_libraries:
  -----------------------------------------------------------------------------
  # Third-party libraries
  -----------------------------
  


  - jekyll-socials
  - jemoji

# -----------------------------------------------------------------------------
# Data Mapping
# -----------------------------------------------------------------------------
jekyll_get_json:
  - data: resume
    json: assets/json/resume.json

jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - awards
  - skills
